- name: Setup shared SSH keys
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Check whether shared SSH key is generated
      stat:
        path: /tmp/id_decode_test
      register: shared_ssh_key_exists

    - name: Generate shared SSH key
      shell: |
        ssh-keygen -t ed25519 -C "noise-cloudlab-benchmark" -f /tmp/id_decode_test -q -N ""
      when: not shared_ssh_key_exists.stat.exists

- hosts: all
  roles:
    - role: local_user
      become: yes
    - role: base
      become: yes
      become_user: localuser

- hosts: decode-node
  roles:
    - role: node
      become: yes
      become_user: localuser

- hosts: decode-coord
  roles:
    - role: elixir-coord
      become: yes
      become_user: localuser

- hosts: decode-client
  roles:
    - role: client
      become: yes
      become_user: localuser

# - hosts: decode-coord
#   become: "yes"
#   roles:
#     - role: local_user
#       become: yes
#     - role: base
#       become: yes
#       become_user: localuser
#     - role: coord
#       become: yes
#       become_user: localuser
#   poll: 0

# - hosts: decode-client
#   become: "yes"
#   roles:
#     - role: local_user
#       become: yes
#     - role: base
#       become: yes
#       become_user: localuser
#     - role: client
#       become: yes
#       become_user: localuser
#   poll: 0
