"""empty message

Revision ID: 8777cd6a82d6
Revises: d9e216be35fd
Create Date: 2022-10-31 18:05:33.563331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8777cd6a82d6'
down_revision = 'd9e216be35fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('object_id', postgresql.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('object_id', 'index')
    )
    op.create_table('shards',
    sa.Column('object_id', postgresql.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('shard_index', sa.Integer(), nullable=False),
    sa.Column('shard_hash', sa.LargeBinary(length=32), nullable=False),
    sa.ForeignKeyConstraint(['chunk_index'], ['chunks.index'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('object_id', 'chunk_index', 'shard_index')
    )
    op.add_column('objects', sa.Column('size', sa.Integer(), nullable=False))
    op.add_column('objects', sa.Column('chunk_size', sa.Integer(), nullable=False))
    op.add_column('objects', sa.Column('shard_size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'shard_size')
    op.drop_column('objects', 'chunk_size')
    op.drop_column('objects', 'size')
    op.drop_table('shards')
    op.drop_table('chunks')
    # ### end Alembic commands ###
