"""empty message

Revision ID: aad9e507ce26
Revises: 
Create Date: 2022-11-02 20:11:33.512204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aad9e507ce26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objects',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('shard_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunks',
    sa.Column('object_id', postgresql.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('object_id', 'chunk_index')
    )
    op.create_table('shards',
    sa.Column('object_id', postgresql.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('shard_index', sa.Integer(), nullable=False),
    sa.Column('shard_hash', sa.LargeBinary(length=32), nullable=False),
    sa.ForeignKeyConstraint(['object_id', 'chunk_index'], ['chunks.object_id', 'chunks.chunk_index'], ),
    sa.PrimaryKeyConstraint('object_id', 'chunk_index', 'shard_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shards')
    op.drop_table('chunks')
    op.drop_table('objects')
    # ### end Alembic commands ###
