"""empty message

Revision ID: b16001c3cc37
Revises: aad9e507ce26
Create Date: 2022-11-02 21:00:36.487748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16001c3cc37'
down_revision = 'aad9e507ce26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('code_ratio_data', sa.Integer(), nullable=False))
    op.add_column('objects', sa.Column('code_ratio_parity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'code_ratio_parity')
    op.drop_column('objects', 'code_ratio_data')
    # ### end Alembic commands ###
