- name: Set as coord
  become: yes
  become_user: root
  command: touch /is-coord

- name: Install PostgreSQL
  become: yes
  become_user: root
  apt:
    name: postgresql
    state: present

- name: Check if decode database exists
  become: yes
  become_user: postgres
  command: psql "decode_coord_dev" -c "\\q"
  failed_when: false
  register: decode_coord_db_check
  changed_when: false

- name: Create decode database and user
  become: yes
  become_user: postgres
  shell: |
    psql -c "CREATE USER decode_coord PASSWORD 'decode_coord'"
    psql -c "CREATE DATABASE decode_coord_dev"
    psql -c "GRANT ALL PRIVILEGES ON DATABASE decode_coord_dev TO decode_coord"
  #when: decode_coord_db_check.rc != 0

- name: Install dependencies for asdf version manager
  become: yes
  become_user: root
  apt:
    name:
      - curl
      - git
      - libncurses5-dev
      - build-essential
    state: present

- name: Install asdf version manager
  git:
    repo: http://github.com/asdf-vm/asdf.git
    dest: /localdisk/localuser/.asdf
    version: v0.10.2
    clone: yes
    update: yes
    force: yes
  register: asdf_git

- name: Install recent Erlang & Elixir through asdf
  shell: |
    . $HOME/.asdf/asdf.sh
    asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
    asdf install erlang latest
    asdf global erlang latest
    asdf plugin add elixir https://github.com/asdf-vm/asdf-elixir.git
    asdf install elixir latest
    asdf global elixir latest
  args:
    executable: /bin/bash
  # when: asdf_git.changed

# mix local.hex --force
# mix local.rebar --force

# - name: Install coordinator dependencies in virtualenv
#   pip:
#     virtualenv: "/localdisk/localuser/decode/.coord_venv"
#     virtualenv_command: "python3 -m venv"
#     requirements: "/localdisk/localuser/decode/coord/requirements.txt"
#     state: present

# - name: Initialize and/or upgrade the database
#   shell: |
#     cd /localdisk/localuser/decode/coord
#     . ../.coord_venv/bin/activate
#     . ./.env
#     export PYTHONPATH="$(readlink -f .):$PYTHONPATH"
#     export DATABASE_URL="postgresql:///decode_coord"
#     flask db upgrade

# - name: Create decode-coord systemd service
#   become: yes
#   become_user: root
#   copy:
#     dest: "/etc/systemd/system/decode-coord.service"
#     mode: "0744"
#     content: |
#       [Unit]
#       Description=DECODE coordinator service
#       Requires=network-online.target

#       [Service]
#       WorkingDirectory=/localdisk/localuser/decode/coord
#       User=localuser
#       ExecStart=/bin/bash -c "source ../.coord_venv/bin/activate; source .env; export PYTHONPATH=\"$(readlink -f .):$PYTHONPATH\"; export DATABASE_URL=\"postgresql:///decode_coord\"; flask run --host 0.0.0.0"

#       [Install]
#       WantedBy=multi-user.target

# - name: Start the decode-coord service
#   become: yes
#   become_user: root
#   systemd:
#     name: decode-coord
#     state: started
#     daemon_reload: true
